export interface SicCode {
  code: string;
  label: string;
  category: string;
}

export const SIC_CODES: SicCode[] = [
  // Agriculture, sylviculture et pêche
  { code: "01110", category: "Agriculture", label: "Culture de céréales (sauf riz), légumineuses et oléagineux" },
  { code: "01120", category: "Agriculture", label: "Culture du riz" },
  { code: "01130", category: "Agriculture", label: "Culture de légumes, melons, tubercules et racines" },
  { code: "01140", category: "Agriculture", label: "Culture de la canne à sucre" },
  { code: "01150", category: "Agriculture", label: "Culture du tabac" },
  { code: "01160", category: "Agriculture", label: "Culture de plantes à fibres" },
  { code: "01190", category: "Agriculture", label: "Autres cultures non permanentes" },
  { code: "01210", category: "Agriculture", label: "Culture de la vigne" },
  { code: "01220", category: "Agriculture", label: "Culture de fruits tropicaux et subtropicaux" },
  { code: "01230", category: "Agriculture", label: "Culture d'agrumes" },
  { code: "01240", category: "Agriculture", label: "Culture de fruits à pépins et à noyau" },
  { code: "01250", category: "Agriculture", label: "Culture d'autres fruits d'arbres, d'arbustes ou cactacées" },
  { code: "01260", category: "Agriculture", label: "Culture de fruits oléagineux" },
  { code: "01270", category: "Agriculture", label: "Culture de plantes pour la préparation de boissons" },
  { code: "01280", category: "Agriculture", label: "Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques" },
  { code: "01290", category: "Agriculture", label: "Autres cultures permanentes" },
  { code: "01500", category: "Agriculture", label: "Culture et élevage associés" },
  { code: "01610", category: "Agriculture", label: "Activités de soutien aux cultures" },
  { code: "01620", category: "Agriculture", label: "Activités de soutien à la production animale" },
  { code: "01630", category: "Agriculture", label: "Traitement primaire des récoltes" },
  { code: "01640", category: "Agriculture", label: "Traitement des semences pour la reproduction" },
  { code: "01700", category: "Agriculture", label: "Chasse, piégeage et activités connexes" },
  { code: "02100", category: "Agriculture", label: "Sylviculture et autres activités forestières" },
  { code: "02200", category: "Agriculture", label: "Exploitation forestière" },
  { code: "02300", category: "Agriculture", label: "Récolte de produits forestiers non ligneux" },
  { code: "02400", category: "Agriculture", label: "Services de soutien à l'exploitation forestière" },
  { code: "03110", category: "Agriculture", label: "Pêche en mer" },
  { code: "03120", category: "Agriculture", label: "Pêche en eau douce" },
  { code: "03210", category: "Agriculture", label: "Aquaculture en mer" },
  { code: "03220", category: "Agriculture", label: "Aquaculture en eau douce" },

  // Industrie extractive
  { code: "05100", category: "Industrie extractive", label: "Extraction de houille" },
  { code: "05200", category: "Industrie extractive", label: "Extraction de lignite" },
  { code: "06100", category: "Industrie extractive", label: "Extraction de pétrole brut" },
  { code: "06200", category: "Industrie extractive", label: "Extraction de gaz naturel" },
  { code: "08110", category: "Industrie extractive", label: "Extraction de pierres ornementales et de construction, de calcaire industriel, de gypse, de craie et d'ardoise" },
  { code: "08120", category: "Industrie extractive", label: "Exploitation de gravières et sablières, extraction d'argiles et de kaolin" },
  { code: "08910", category: "Industrie extractive", label: "Extraction des minéraux chimiques et engrais minéraux" },
  { code: "08920", category: "Industrie extractive", label: "Extraction de tourbe" },
  { code: "08930", category: "Industrie extractive", label: "Production de sel" },
  { code: "08990", category: "Industrie extractive", label: "Autres activités extractives n.c.a." },

  // Construction
  { code: "41100", category: "Construction", label: "Promotion immobilière" },
  { code: "41200", category: "Construction", label: "Construction de bâtiments résidentiels et non résidentiels" },
  { code: "42110", category: "Construction", label: "Construction de routes et autoroutes" },
  { code: "42120", category: "Construction", label: "Construction de voies ferrées de surface et souterraines" },
  { code: "42130", category: "Construction", label: "Construction de ponts et tunnels" },
  { code: "42210", category: "Construction", label: "Construction de réseaux pour fluides" },
  { code: "42220", category: "Construction", label: "Construction de réseaux électriques et de télécommunications" },
  { code: "42910", category: "Construction", label: "Construction d'ouvrages maritimes et fluviaux" },
  { code: "42990", category: "Construction", label: "Construction d'autres ouvrages de génie civil n.c.a." },
  { code: "43110", category: "Construction", label: "Travaux de démolition" },
  { code: "43120", category: "Construction", label: "Travaux de préparation des sites" },
  { code: "43130", category: "Construction", label: "Forages et sondages" },
  { code: "43210", category: "Construction", label: "Installation électrique" },
  { code: "43220", category: "Construction", label: "Travaux de plomberie et installation de chauffage et de conditionnement d'air" },
  { code: "43290", category: "Construction", label: "Autres travaux d'installation" },
  { code: "43310", category: "Construction", label: "Réalisation de chapes" },
  { code: "43320", category: "Construction", label: "Travaux de menuiserie" },
  { code: "43330", category: "Construction", label: "Travaux de revêtement des sols et des murs" },
  { code: "43341", category: "Construction", label: "Travaux de peinture" },
  { code: "43342", category: "Construction", label: "Travaux de vitrerie" },
  { code: "43390", category: "Construction", label: "Autres travaux de finition" },
  { code: "43910", category: "Construction", label: "Travaux de couverture" },
  { code: "43990", category: "Construction", label: "Autres travaux de construction spécialisés n.c.a." },

  // Commerce
  { code: "45111", category: "Commerce", label: "Commerce de voitures et de véhicules automobiles légers" },
  { code: "45112", category: "Commerce", label: "Commerce de voitures et de véhicules automobiles légers (commerce de détail)" },
  { code: "45190", category: "Commerce", label: "Commerce d'autres véhicules automobiles" },
  { code: "45200", category: "Commerce", label: "Entretien et réparation de véhicules automobiles" },
  { code: "45310", category: "Commerce", label: "Commerce de gros d'équipements automobiles" },
  { code: "45320", category: "Commerce", label: "Commerce de détail d'équipements automobiles" },
  { code: "45400", category: "Commerce", label: "Commerce et réparation de motocycles" },
  { code: "46100", category: "Commerce", label: "Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis" },
  { code: "46110", category: "Commerce", label: "Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis" },
  { code: "46120", category: "Commerce", label: "Intermédiaires du commerce en combustibles, métaux, minéraux et produits chimiques" },
  { code: "46130", category: "Commerce", label: "Intermédiaires du commerce en bois et matériaux de construction" },
  { code: "46140", category: "Commerce", label: "Intermédiaires du commerce en machines, équipements industriels, navires et avions" },
  { code: "46150", category: "Commerce", label: "Intermédiaires du commerce en meubles, articles ménagers et quincaillerie" },
  { code: "46160", category: "Commerce", label: "Intermédiaires du commerce en textiles, habillement, fourrures, chaussures et articles en cuir" },
  { code: "46170", category: "Commerce", label: "Intermédiaires du commerce en denrées, boissons et tabac" },
  { code: "46180", category: "Commerce", label: "Intermédiaires du commerce spécialisés dans d'autres produits" },
  { code: "46190", category: "Commerce", label: "Intermédiaires du commerce en produits divers" },
  { code: "47190", category: "Commerce", label: "Autres commerces de détail en magasin non spécialisé" },
  { code: "47410", category: "Commerce", label: "Commerce de détail d'ordinateurs, d'unités périphériques et de logiciels en magasin spécialisé" },
  { code: "47420", category: "Commerce", label: "Commerce de détail de matériels de télécommunication en magasin spécialisé" },
  { code: "47430", category: "Commerce", label: "Commerce de détail de matériels audio et vidéo en magasin spécialisé" },
  { code: "47520", category: "Commerce", label: "Commerce de détail de quincaillerie, peintures et verres en magasin spécialisé" },
  { code: "47640", category: "Commerce", label: "Commerce de détail d'articles de sport en magasin spécialisé" },
  { code: "47650", category: "Commerce", label: "Commerce de détail de jeux et jouets en magasin spécialisé" },
  { code: "47710", category: "Commerce", label: "Commerce de détail d'habillement en magasin spécialisé" },
  { code: "47720", category: "Commerce", label: "Commerce de détail de chaussures et d'articles en cuir en magasin spécialisé" },
  { code: "47730", category: "Commerce", label: "Commerce de détail de produits pharmaceutiques en magasin spécialisé" },
  { code: "47740", category: "Commerce", label: "Commerce de détail d'articles médicaux et orthopédiques en magasin spécialisé" },
  { code: "47750", category: "Commerce", label: "Commerce de détail de parfumerie et de produits de beauté en magasin spécialisé" },
  { code: "47760", category: "Commerce", label: "Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux en magasin spécialisé" },
  { code: "47770", category: "Commerce", label: "Commerce de détail d'articles d'horlogerie et de bijouterie en magasin spécialisé" },
  { code: "47781", category: "Commerce", label: "Commerces de détail d'optique" },
  { code: "47782", category: "Commerce", label: "Commerce de détail de charbons et combustibles domestiques en magasin spécialisé" },
  { code: "47789", category: "Commerce", label: "Autres commerces de détail de nouveautés et d'articles divers en magasin spécialisé" },
  { code: "47791", category: "Commerce", label: "Commerce de détail de livres d'occasion en magasin spécialisé" },
  { code: "47799", category: "Commerce", label: "Autres commerces de détail de biens d'occasion en magasin" },
  { code: "47910", category: "Commerce", label: "Vente à distance sur catalogue général ou thématique" },
  { code: "47990", category: "Commerce", label: "Autres commerces de détail hors magasin, éventaires ou marchés" },

  // Technologies / informatique
  { code: "58110", category: "Technologies / IT", label: "Édition de livres" },
  { code: "58120", category: "Technologies / IT", label: "Édition de répertoires et de fichiers d'adresses" },
  { code: "58130", category: "Technologies / IT", label: "Édition de journaux" },
  { code: "58141", category: "Technologies / IT", label: "Édition de revues et périodiques" },
  { code: "58142", category: "Technologies / IT", label: "Édition de revues et publications périodiques" },
  { code: "58190", category: "Technologies / IT", label: "Autres activités d'édition" },
  { code: "58210", category: "Technologies / IT", label: "Édition de jeux électroniques" },
  { code: "58290", category: "Technologies / IT", label: "Édition d'autres logiciels" },
  { code: "59110", category: "Technologies / IT", label: "Production de films cinématographiques" },
  { code: "59120", category: "Technologies / IT", label: "Post-production de films cinématographiques, de vidéo et de programmes de télévision" },
  { code: "59130", category: "Technologies / IT", label: "Distribution de films cinématographiques et d'autres films et programmes" },
  { code: "59140", category: "Technologies / IT", label: "Projection de films cinématographiques" },
  { code: "59200", category: "Technologies / IT", label: "Enregistrement sonore et édition musicale" },
  { code: "60100", category: "Technologies / IT", label: "Édition et diffusion de programmes radio" },
  { code: "60200", category: "Technologies / IT", label: "Programmation de télévision et télédiffusion" },
  { code: "61100", category: "Technologies / IT", label: "Télécommunications filaires" },
  { code: "61200", category: "Technologies / IT", label: "Télécommunications sans fil" },
  { code: "61300", category: "Technologies / IT", label: "Télécommunications par satellite" },
  { code: "61900", category: "Technologies / IT", label: "Autres activités de télécommunication" },
  { code: "62011", category: "Technologies / IT", label: "Activités de programmation informatique" },
  { code: "62012", category: "Technologies / IT", label: "Développement et production de logiciels prêts à l'emploi" },
  { code: "62020", category: "Technologies / IT", label: "Conseil informatique" },
  { code: "62030", category: "Technologies / IT", label: "Gestion d'installations informatiques" },
  { code: "62090", category: "Technologies / IT", label: "Autres activités informatiques" },
  { code: "63110", category: "Technologies / IT", label: "Traitement de données, hébergement et activités connexes" },
  { code: "63120", category: "Technologies / IT", label: "Portails internet" },
  { code: "63910", category: "Technologies / IT", label: "Activités des agences de presse" },
  { code: "63990", category: "Technologies / IT", label: "Autres services d'information n.c.a." },

  // Finance et assurance
  { code: "64110", category: "Finance & Assurance", label: "Activités de banque centrale" },
  { code: "64190", category: "Finance & Assurance", label: "Autres intermédiations monétaires" },
  { code: "64200", category: "Finance & Assurance", label: "Activités des sociétés holding" },
  { code: "64301", category: "Finance & Assurance", label: "Fonds de placement fermés" },
  { code: "64302", category: "Finance & Assurance", label: "Sociétés de capital-risque" },
  { code: "64303", category: "Finance & Assurance", label: "Activités des véhicules à usage spécial" },
  { code: "64304", category: "Finance & Assurance", label: "Activités des SICAV et FCP" },
  { code: "64910", category: "Finance & Assurance", label: "Crédit-bail" },
  { code: "64920", category: "Finance & Assurance", label: "Autre distribution de crédit" },
  { code: "64991", category: "Finance & Assurance", label: "Activités des sociétés de portefeuille (à usage non financier)" },
  { code: "64999", category: "Finance & Assurance", label: "Autres services financiers n.c.a." },
  { code: "65110", category: "Finance & Assurance", label: "Assurance vie" },
  { code: "65120", category: "Finance & Assurance", label: "Autres assurances" },
  { code: "65201", category: "Finance & Assurance", label: "Réassurance vie" },
  { code: "65202", category: "Finance & Assurance", label: "Réassurance non-vie" },
  { code: "65300", category: "Finance & Assurance", label: "Caisses de retraite" },
  { code: "66110", category: "Finance & Assurance", label: "Gestion de marchés financiers" },
  { code: "66120", category: "Finance & Assurance", label: "Courtage de valeurs mobilières et de marchandises" },
  { code: "66190", category: "Finance & Assurance", label: "Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite" },
  { code: "66210", category: "Finance & Assurance", label: "Évaluation des risques et dommages" },
  { code: "66220", category: "Finance & Assurance", label: "Activités des agents et courtiers d'assurances" },
  { code: "66290", category: "Finance & Assurance", label: "Autres activités auxiliaires d'assurance et de caisses de retraite" },
  { code: "66300", category: "Finance & Assurance", label: "Gestion de fonds" },

  // Immobilier
  { code: "68100", category: "Immobilier", label: "Activités des marchands de biens immobiliers" },
  { code: "68201", category: "Immobilier", label: "Location et exploitation de logements propres ou loués" },
  { code: "68202", category: "Immobilier", label: "Location et exploitation de terrains et d'autres biens immobiliers propres ou loués" },
  { code: "68209", category: "Immobilier", label: "Autres locations et exploitations de biens immobiliers propres ou loués" },
  { code: "68310", category: "Immobilier", label: "Agences immobilières" },
  { code: "68320", category: "Immobilier", label: "Administration de biens immobiliers" },

  // Consulting / juridique / comptabilité
  { code: "69101", category: "Consulting / Juridique", label: "Activités des avocats" },
  { code: "69102", category: "Consulting / Juridique", label: "Activités des notaires" },
  { code: "69109", category: "Consulting / Juridique", label: "Autres activités juridiques" },
  { code: "69201", category: "Consulting / Juridique", label: "Activités des experts-comptables et des commissaires aux comptes" },
  { code: "69202", category: "Consulting / Juridique", label: "Activités des comptables" },
  { code: "69203", category: "Consulting / Juridique", label: "Activités des gestionnaires de paie" },
  { code: "70100", category: "Consulting / Juridique", label: "Activités des sièges sociaux" },
  { code: "70210", category: "Consulting / Juridique", label: "Conseil en relations publiques et communication" },
  { code: "70221", category: "Consulting / Juridique", label: "Conseil en stratégie et management des entreprises" },
  { code: "70222", category: "Consulting / Juridique", label: "Ingénierie des systèmes d'information" },
  { code: "71111", category: "Consulting / Juridique", label: "Activités d'architecture" },
  { code: "71112", category: "Consulting / Juridique", label: "Activités d'ingénierie" },
  { code: "71121", category: "Consulting / Juridique", label: "Activités des géomètres" },
  { code: "71122", category: "Consulting / Juridique", label: "Prospection géophysique" },
  { code: "71129", category: "Consulting / Juridique", label: "Autres activités d'ingénierie, études techniques" },
  { code: "71200", category: "Consulting / Juridique", label: "Activités de contrôle et analyses techniques" },
  { code: "72110", category: "Consulting / Juridique", label: "Recherche-développement en biotechnologie" },
  { code: "72190", category: "Consulting / Juridique", label: "Autre recherche-développement en sciences physiques et naturelles" },
  { code: "72200", category: "Consulting / Juridique", label: "Recherche-développement en sciences humaines et sociales" },
  { code: "73110", category: "Consulting / Juridique", label: "Activités des agences de publicité" },
  { code: "73120", category: "Consulting / Juridique", label: "Régie publicitaire de médias" },
  { code: "73200", category: "Consulting / Juridique", label: "Études de marché et sondages d'opinion" },
  { code: "74100", category: "Consulting / Juridique", label: "Activités spécialisées de design" },
  { code: "74200", category: "Consulting / Juridique", label: "Activités photographiques" },
  { code: "74300", category: "Consulting / Juridique", label: "Traduction et interprétation" },
  { code: "74901", category: "Consulting / Juridique", label: "Activités des agents commerciaux" },
  { code: "74902", category: "Consulting / Juridique", label: "Activités des détectives privés" },
  { code: "74909", category: "Consulting / Juridique", label: "Autres activités professionnelles, scientifiques et techniques n.c.a." },

  // Services administratifs
  { code: "77110", category: "Services administratifs", label: "Location et location-bail de voitures et de véhicules automobiles légers" },
  { code: "77120", category: "Services administratifs", label: "Location et location-bail de camions" },
  { code: "77210", category: "Services administratifs", label: "Location et location-bail d'articles de loisirs et de sport" },
  { code: "77220", category: "Services administratifs", label: "Location de cassettes vidéo et disques" },
  { code: "77290", category: "Services administratifs", label: "Location et location-bail d'autres biens personnels et domestiques" },
  { code: "77310", category: "Services administratifs", label: "Location et location-bail de machines et équipements agricoles" },
  { code: "77320", category: "Services administratifs", label: "Location et location-bail de machines et équipements pour la construction" },
  { code: "77330", category: "Services administratifs", label: "Location et location-bail de machines de bureau et matériel informatique" },
  { code: "77340", category: "Services administratifs", label: "Location et location-bail de matériels de transport par eau" },
  { code: "77350", category: "Services administratifs", label: "Location et location-bail de matériels de transport aérien" },
  { code: "77390", category: "Services administratifs", label: "Location et location-bail d'autres machines, équipements et biens matériels n.c.a." },
  { code: "77400", category: "Services administratifs", label: "Location-bail de propriété intellectuelle et de produits similaires, à l'exception des oeuvres soumises à copyright" },
  { code: "78100", category: "Services administratifs", label: "Activités des agences de placement de main-d'oeuvre" },
  { code: "78200", category: "Services administratifs", label: "Activités des agences de travail temporaire" },
  { code: "78300", category: "Services administratifs", label: "Autre mise à disposition de ressources humaines" },
  { code: "79110", category: "Services administratifs", label: "Activités des agences de voyage" },
  { code: "79120", category: "Services administratifs", label: "Activités des voyagistes" },
  { code: "79900", category: "Services administratifs", label: "Autres services de réservation et activités connexes" },
  { code: "80100", category: "Services administratifs", label: "Activités de sécurité privée" },
  { code: "80200", category: "Services administratifs", label: "Activités des systèmes de sécurité" },
  { code: "80300", category: "Services administratifs", label: "Activités d'enquête" },
  { code: "81100", category: "Services administratifs", label: "Activités combinées de soutien lié aux bâtiments" },
  { code: "81210", category: "Services administratifs", label: "Nettoyage courant des bâtiments" },
  { code: "81220", category: "Services administratifs", label: "Autres activités de nettoyage des bâtiments et nettoyage industriel" },
  { code: "81290", category: "Services administratifs", label: "Autres activités de nettoyage" },
  { code: "81300", category: "Services administratifs", label: "Services d'aménagement paysager" },
  { code: "82110", category: "Services administratifs", label: "Services administratifs combinés de bureau" },
  { code: "82190", category: "Services administratifs", label: "Photocopie, préparation de documents et autres activités spécialisées de soutien de bureau" },
  { code: "82200", category: "Services administratifs", label: "Activités de centres d'appels" },
  { code: "82300", category: "Services administratifs", label: "Organisation de salons professionnels et de congrès" },
  { code: "82910", category: "Services administratifs", label: "Activités des agences de recouvrement de factures et des sociétés d'information financière sur la clientèle" },
  { code: "82920", category: "Services administratifs", label: "Activités de conditionnement" },
  { code: "82990", category: "Services administratifs", label: "Autres activités de soutien aux entreprises n.c.a." },

  // Santé
  { code: "86100", category: "Santé", label: "Activités hospitalières" },
  { code: "86210", category: "Santé", label: "Activité des médecins généralistes" },
  { code: "86220", category: "Santé", label: "Activité des médecins spécialistes" },
  { code: "86230", category: "Santé", label: "Pratique dentaire" },
  { code: "86290", category: "Santé", label: "Autres activités pour la santé humaine" },
  { code: "86900", category: "Santé", label: "Autres activités pour la santé humaine" },
  { code: "87100", category: "Santé", label: "Hébergement médicalisé" },
  { code: "87200", category: "Santé", label: "Hébergement social pour personnes handicapées mentales, malades mentales et toxicomanes" },
  { code: "87300", category: "Santé", label: "Hébergement social pour personnes âgées ou handicapées physiques" },
  { code: "87900", category: "Santé", label: "Autres formes d'hébergement social" },
  { code: "88100", category: "Santé", label: "Action sociale sans hébergement pour personnes âgées et pour personnes handicapées" },
  { code: "88910", category: "Santé", label: "Accueil de jeunes enfants" },
  { code: "88990", category: "Santé", label: "Autre action sociale sans hébergement n.c.a." },

  // Éducation / formation
  { code: "85100", category: "Éducation / Formation", label: "Enseignement pré-primaire" },
  { code: "85200", category: "Éducation / Formation", label: "Enseignement primaire" },
  { code: "85310", category: "Éducation / Formation", label: "Enseignement secondaire général" },
  { code: "85320", category: "Éducation / Formation", label: "Enseignement secondaire technique ou professionnel" },
  { code: "85410", category: "Éducation / Formation", label: "Enseignement post-secondaire non supérieur" },
  { code: "85420", category: "Éducation / Formation", label: "Enseignement supérieur" },
  { code: "85510", category: "Éducation / Formation", label: "Enseignement de disciplines sportives et d'activités de loisirs" },
  { code: "85520", category: "Éducation / Formation", label: "Enseignement culturel" },
  { code: "85530", category: "Éducation / Formation", label: "Enseignement de la conduite" },
  { code: "85590", category: "Éducation / Formation", label: "Autres enseignements" },
  { code: "85600", category: "Éducation / Formation", label: "Activités de soutien à l'enseignement" },

  // Hôtellerie / restauration
  { code: "55100", category: "Hôtellerie / Restauration", label: "Hôtels et hébergement similaire" },
  { code: "55200", category: "Hôtellerie / Restauration", label: "Hébergement touristique et autre hébergement de courte durée" },
  { code: "55300", category: "Hôtellerie / Restauration", label: "Terrains de camping et parcs pour caravanes ou véhicules de loisirs" },
  { code: "55900", category: "Hôtellerie / Restauration", label: "Autres hébergements" },
  { code: "56101", category: "Hôtellerie / Restauration", label: "Restauration traditionnelle" },
  { code: "56102", category: "Hôtellerie / Restauration", label: "Cafés tabacs" },
  { code: "56103", category: "Hôtellerie / Restauration", label: "Restauration de type rapide" },
  { code: "56210", category: "Hôtellerie / Restauration", label: "Services des traiteurs et des organisations de réceptions" },
  { code: "56290", category: "Hôtellerie / Restauration", label: "Autres services de restauration" },
  { code: "56301", category: "Hôtellerie / Restauration", label: "Débits de boissons" },
  { code: "56302", category: "Hôtellerie / Restauration", label: "Bars-tabacs" },
];

export function getSicCategories(): string[] {
  return [...new Set(SIC_CODES.map((c) => c.category))];
}

export function getSicCodesByCategory(): Record<string, SicCode[]> {
  return SIC_CODES.reduce<Record<string, SicCode[]>>((acc, code) => {
    if (!acc[code.category]) acc[code.category] = [];
    acc[code.category].push(code);
    return acc;
  }, {});
}
