"use client";

import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "fr" | "en";

const T = {
  fr: {
    "nav.dashboard": "Tableau de bord",
    "nav.clients": "Clients",
    "nav.agents": "Agents",
    "nav.companyRequests": "Créations société",
    "nav.documents": "Documents",
    "nav.invoices": "Factures",
    "nav.commissions": "Commissions",
    "nav.contracts": "Contrats / CGV",
    "nav.atlasCircle": "Atlas Circle",
    "nav.settings": "Paramètres",
    "nav.tickets": "Support",
    "nav.bankAccount": "Compte bancaire",
    "nav.services": "Services web",
    "nav.profile": "Mon profil",
    "status.draft": "Brouillon",
    "status.info_submitted": "Infos soumises",
    "status.kyc_required": "Pièces d'identité requises",
    "status.kyc_in_review": "Dossier en examen",
    "status.identity_verification": "Vérification d'identité",
    "status.submitted_companies_house": "Soumis succursale",
    "status.company_created": "Société créée ✓",
    "status.branch_preparation": "Création succursale",
    "status.completed": "Terminé ✓",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.close": "Fermer",
    "common.submit": "Soumettre",
    "common.loading": "Chargement…",
    "common.download": "Télécharger",
    "common.upload": "Déposer un fichier",
    "common.newTicket": "Nouveau ticket",
    "ticket.subject": "Sujet",
    "ticket.open": "Ouvert",
    "ticket.in_progress": "En cours",
    "ticket.resolved": "Résolu",
    "ticket.closed": "Fermé",
    "ticket.priority.low": "Faible",
    "ticket.priority.normal": "Normale",
    "ticket.priority.high": "Haute",
    "ticket.priority.urgent": "Urgente",
    "ticket.reply": "Envoyer le message",
    "ticket.placeholder": "Votre message…",
    "bank.title": "Compte bancaire Revolut Business",
    "bank.subtitle": "Configurez votre compte bancaire professionnel",
    "bank.email": "Email Revolut",
    "bank.phone": "Numéro de téléphone",
    "bank.pin": "Code secret (6 chiffres)",
    "bank.submit": "Créer mon compte bancaire",
    "bank.pending": "Demande en cours de traitement",
    "bank.active": "Compte actif",
    "kyc.title": "Pièces d'identité requises",
    "kyc.subtitle": "Pour finaliser votre dossier, veuillez fournir les documents suivants. Vous pouvez prendre une photo depuis votre mobile ou importer depuis votre galerie.",
    "kyc.doc1": "Passeport ou Carte Nationale d'Identité (recto-verso)",
    "kyc.doc2": "Justificatif de domicile de moins de 3 mois (facture EDF, quittance de loyer…)",
    "kyc.doc3": "Si actionnaire société : extrait Kbis ou équivalent",
    "kyc.submit": "Soumettre mes documents",
    "kyc.submitted": "Documents envoyés — dossier en cours d'examen",
    "kyc.addFile": "Ajouter un document (photo ou fichier)",
    "kyc.docType": "Type de document",
    "kyc.docType.passport": "Passeport",
    "kyc.docType.national_id": "Carte d'identité",
    "kyc.docType.residence_permit": "Titre de séjour",
    "kyc.docType.drivers_license": "Permis de conduire",
    "kyc.docType.proof_of_address": "Justificatif d'adresse",
    "kyc.docType.kbis": "Extrait Kbis",
    "kyc.identityVerifTitle": "Vérification d'identité en cours",
    "kyc.identityVerifDesc": "Vos documents ont été reçus. Un opérateur Atlas vous contactera prochainement pour finaliser la vérification de votre identité.",
    "branch.title": "Informations pour la succursale",
    "branch.subtitle": "Renseignez l'adresse de votre succursale et les justificatifs",
    "branch.address": "Adresse de la succursale",
    "branch.proofType": "Type de justificatif",
    "branch.bail": "Bail à loyer",
    "branch.facture": "Facture d'électricité",
    "branch.autre": "Autre document",
    "branch.submit": "Soumettre les informations",
    "branch.canton": "Canton de la succursale",
    "company.info": "Informations officielles de la société",
    "company.number": "Numéro Companies House",
    "company.nameFinal": "Nom officiel de la société",
    "company.incorp": "Date d'immatriculation",
    "company.address": "Adresse officielle enregistrée",
    "company.docs": "Documents officiels",
    "services.title": "Services web & digital",
    "services.subtitle": "Solutions numériques par Nexus Sphère Studio",
    "services.requestQuote": "Demander un devis",
    "services.priceFrom": "À partir de",
    "services.priceMonthly": "/mois",
    "services.priceFixed": "forfait",
    "services.priceQuote": "Sur devis",
    "services.category.web": "Site web",
    "services.category.hosting": "Hébergement",
    "services.category.software": "Logiciels & IA",
    "services.category.marketing": "Marketing",
    "services.category.security": "Sécurité",
    "services.category.consulting": "Consulting",
    "services.quoteSuccess": "Demande envoyée ! Notre équipe vous contactera rapidement.",
    "company.pageTitle": "Mes Sociétés",
    "company.addCompany": "Ajouter une société",
    "company.status.active": "Active",
    "company.status.dormant": "Dormante",
    "company.status.dissolved": "Dissoute",
    "company.status.in_dissolution": "En dissolution",
    "company.compliance": "Mise en conformité annuelle",
    "company.complianceWarning": "⚠️ Attention : le non-respect du renouvellement annuel est passible d'une amende de 4 000 £ auprès de Companies House. Le client est seul responsable du respect de cette obligation.",
    "company.complianceDue": "Échéance renouvellement",
    "company.complianceRenew": "Créer facture renouvellement",
    "company.accountingPack": "Pack comptabilité UK",
    "company.accountingDesc": "Comptabilité annuelle réalisée en Angleterre par notre partenaire",
    "company.dissolution": "Résiliation de la société",
    "company.dissolutionDesc": "Dissolution volontaire de la société LTD auprès de Companies House",
    "company.dissolutionCta": "Demander la résiliation",
    "company.dissolutionWarning": "Cette action entraîne la dissolution définitive de la société. Des frais de",
    "company.noBranch": "Aucune succursale enregistrée",
    "company.documents": "Documents de la société",
    "company.branchDocuments": "Documents succursale",
    "company.uploadDoc": "Ajouter un document",
    "company.complianceSoon": "Renouvellement dans moins de 2 mois",
    "company.complianceOverdue": "Renouvellement en retard !",
    "nav.companies": "Mes Sociétés",
    "nav.serviceRequests": "Demandes services",
    "sr.title": "Demandes de services",
    "sr.status.pending": "En attente",
    "sr.status.reviewing": "En cours",
    "sr.status.quoted": "Devis envoyé",
    "sr.status.accepted": "Accepté",
    "sr.status.rejected": "Refusé",
    "sr.status.completed": "Terminé",
    "sr.reply": "Répondre au client",
    "sr.quote": "Envoyer un devis",
    "sr.circleValue": "Valeur Atlas Circle",
    "sr.addCircle": "Ajouter des points Circle",
    "sr.circleAdded": "Points Circle ajoutés",
    "sr.nexusNote": "Le partenaire Nexus Sphère Studio vous contactera directement pour l'offre finale.",
    "sr.clientMessage": "Message du client",
    "sr.adminReply": "Réponse Atlas",
    "services.addService": "Ajouter un service",
    "services.editService": "Modifier le service",
    "nav.more": "Plus",
    "invoice.paymentLink": "Lien de paiement",
    "invoice.payViaLink": "Payer via le lien",
    "invoice.markAsPaid": "J'ai effectué le paiement",
    "invoice.paymentClaimedInfo": "Vous avez déclaré avoir effectué le paiement. Notre équipe va vérifier la réception des fonds.",
    "invoice.confirmPayment": "Confirmer la réception du paiement",
    "invoice.paymentConfirmed": "Paiement confirmé",
    "invoice.setPaymentLink": "Lien de paiement (Revolut, virement…)",
    "status.payment_claimed": "Paiement déclaré",
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Tout marquer lu",
    "notifications.empty": "Aucune notification",
  },
  en: {
    "nav.dashboard": "Dashboard",
    "nav.clients": "Clients",
    "nav.agents": "Agents",
    "nav.companyRequests": "Company setup",
    "nav.documents": "Documents",
    "nav.invoices": "Invoices",
    "nav.commissions": "Commissions",
    "nav.contracts": "Contracts / T&C",
    "nav.atlasCircle": "Atlas Circle",
    "nav.settings": "Settings",
    "nav.tickets": "Support",
    "nav.bankAccount": "Bank account",
    "nav.services": "Web services",
    "nav.profile": "My Profile",
    "status.draft": "Draft",
    "status.info_submitted": "Info submitted",
    "status.kyc_required": "Identity documents required",
    "status.kyc_in_review": "File under review",
    "status.identity_verification": "Identity verification",
    "status.submitted_companies_house": "Branch submitted",
    "status.company_created": "Company created ✓",
    "status.branch_preparation": "Branch setup",
    "status.completed": "Completed ✓",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.submit": "Submit",
    "common.loading": "Loading…",
    "common.download": "Download",
    "common.upload": "Upload file",
    "common.newTicket": "New ticket",
    "ticket.subject": "Subject",
    "ticket.open": "Open",
    "ticket.in_progress": "In progress",
    "ticket.resolved": "Resolved",
    "ticket.closed": "Closed",
    "ticket.priority.low": "Low",
    "ticket.priority.normal": "Normal",
    "ticket.priority.high": "High",
    "ticket.priority.urgent": "Urgent",
    "ticket.reply": "Send message",
    "ticket.placeholder": "Your message…",
    "bank.title": "Revolut Business Bank Account",
    "bank.subtitle": "Set up your professional bank account",
    "bank.email": "Revolut Email",
    "bank.phone": "Phone number",
    "bank.pin": "Secret code (6 digits)",
    "bank.submit": "Create my bank account",
    "bank.pending": "Request being processed",
    "bank.active": "Account active",
    "kyc.title": "Identity documents required",
    "kyc.subtitle": "To finalise your file, please provide the following documents. You can take a photo directly from your mobile or import from your gallery.",
    "kyc.doc1": "Passport or National ID card (front & back)",
    "kyc.doc2": "Proof of address less than 3 months old (utility bill, rent receipt…)",
    "kyc.doc3": "If corporate shareholder: Kbis extract or equivalent",
    "kyc.submit": "Submit my documents",
    "kyc.submitted": "Documents submitted — file under review",
    "kyc.addFile": "Add a document (photo or file)",
    "kyc.docType": "Document type",
    "kyc.docType.passport": "Passport",
    "kyc.docType.national_id": "National ID card",
    "kyc.docType.residence_permit": "Residence permit",
    "kyc.docType.drivers_license": "Driver's licence",
    "kyc.docType.proof_of_address": "Proof of address",
    "kyc.docType.kbis": "Kbis extract",
    "kyc.identityVerifTitle": "Identity verification in progress",
    "kyc.identityVerifDesc": "Your documents have been received. An Atlas operator will contact you shortly to finalise your identity verification.",
    "branch.title": "Branch information",
    "branch.subtitle": "Provide your branch address and supporting documents",
    "branch.address": "Branch address",
    "branch.proofType": "Proof type",
    "branch.bail": "Lease agreement",
    "branch.facture": "Electricity bill",
    "branch.autre": "Other document",
    "branch.submit": "Submit information",
    "branch.canton": "Branch canton",
    "company.info": "Official company information",
    "company.number": "Companies House number",
    "company.nameFinal": "Official company name",
    "company.incorp": "Incorporation date",
    "company.address": "Registered address",
    "company.docs": "Official documents",
    "services.title": "Web & digital services",
    "services.subtitle": "Digital solutions by Nexus Sphère Studio",
    "services.requestQuote": "Request a quote",
    "services.priceFrom": "From",
    "services.priceMonthly": "/month",
    "services.priceFixed": "flat rate",
    "services.priceQuote": "On quote",
    "services.category.web": "Website",
    "services.category.hosting": "Hosting",
    "services.category.software": "Software & AI",
    "services.category.marketing": "Marketing",
    "services.category.security": "Security",
    "services.category.consulting": "Consulting",
    "services.quoteSuccess": "Request sent! Our team will contact you shortly.",
    "company.pageTitle": "My Companies",
    "company.addCompany": "Add a company",
    "company.status.active": "Active",
    "company.status.dormant": "Dormant",
    "company.status.dissolved": "Dissolved",
    "company.status.in_dissolution": "In dissolution",
    "company.compliance": "Annual compliance renewal",
    "company.complianceWarning": "⚠️ Warning: failure to comply with the annual renewal is liable to a £4,000 fine from Companies House. The client is solely responsible for complying with this obligation.",
    "company.complianceDue": "Renewal deadline",
    "company.complianceRenew": "Create renewal invoice",
    "company.accountingPack": "UK accounting pack",
    "company.accountingDesc": "Annual accounting carried out in England by our partner",
    "company.dissolution": "Company dissolution",
    "company.dissolutionDesc": "Voluntary dissolution of the LTD company at Companies House",
    "company.dissolutionCta": "Request dissolution",
    "company.dissolutionWarning": "This will permanently dissolve the company. Fees:",
    "company.noBranch": "No branch registered",
    "company.documents": "Company documents",
    "company.branchDocuments": "Branch documents",
    "company.uploadDoc": "Add a document",
    "company.complianceSoon": "Renewal in less than 2 months",
    "company.complianceOverdue": "Renewal overdue!",
    "nav.companies": "My Companies",
    "nav.serviceRequests": "Service requests",
    "sr.title": "Service requests",
    "sr.status.pending": "Pending",
    "sr.status.reviewing": "Reviewing",
    "sr.status.quoted": "Quoted",
    "sr.status.accepted": "Accepted",
    "sr.status.rejected": "Rejected",
    "sr.status.completed": "Completed",
    "sr.reply": "Reply to client",
    "sr.quote": "Send a quote",
    "sr.circleValue": "Atlas Circle value",
    "sr.addCircle": "Add Circle points",
    "sr.circleAdded": "Circle points added",
    "sr.nexusNote": "The Nexus Sphère Studio partner will contact you directly for the final offer.",
    "sr.clientMessage": "Client message",
    "sr.adminReply": "Atlas reply",
    "services.addService": "Add a service",
    "services.editService": "Edit service",
    "nav.more": "More",
    "invoice.paymentLink": "Payment link",
    "invoice.payViaLink": "Pay via link",
    "invoice.markAsPaid": "I have made the payment",
    "invoice.paymentClaimedInfo": "You have declared your payment. Our team will verify receipt of the funds.",
    "invoice.confirmPayment": "Confirm payment receipt",
    "invoice.paymentConfirmed": "Payment confirmed",
    "invoice.setPaymentLink": "Payment link (Revolut, transfer…)",
    "status.payment_claimed": "Payment declared",
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all read",
    "notifications.empty": "No notifications yet",
  },
} as const;

type TKey = keyof typeof T.fr;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TKey) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "fr",
  setLang: () => {},
  t: (key) => T.fr[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("fr");

  useEffect(() => {
    const saved = localStorage.getItem("atlas_lang") as Lang | null;
    if (saved === "fr" || saved === "en") setLangState(saved);
  }, []);

  function setLang(l: Lang) {
    setLangState(l);
    localStorage.setItem("atlas_lang", l);
  }

  function t(key: TKey): string {
    return (T[lang] as Record<TKey, string>)[key] ?? (T.fr as Record<TKey, string>)[key] ?? key;
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
